name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.3.2
  - pytest=8.4.2
  - scipy=1.16.1
  - pip=24.3.1
  - numpy<2.0
  - pip:
      - mlflow==3.15.1
      - wandb==0.16.4
